version: 0.0
os: linux	
files:	
  - source: /index.html	 
  - source: /css
  - source: /js
  - source: /scripts
    destination: /var/www/html/	    
    destination: /var/www/html/	  
    destination: /var/www/html/	  
    destination: /var/www/html/	  
hooks:	
  BeforeInstall:	 
    - location: /scripts/install_dependencies	   
      timeout: 300	     
      runas: root	     
    - location: /scripts/start_server	    
      timeout: 300	     
      runas: root	      
